name: Trigger S3 Upload

on:
  push:
    branches:
      - main
      - dev-build
  workflow_dispatch:

jobs:
  call-reusable-main:
    if: github.ref == 'refs/heads/main'
    uses: UnityGames-UPS/unity-build-pipeline/.github/workflows/main.yml@main
    with:
      s3_folder: SL-VIK

  call-reusable-dev-build:
    if: github.ref == 'refs/heads/dev-build'
    uses: UnityGames-UPS/unity-build-pipeline/.github/workflows/main.yml@main
    with:
      s3_folder: dev/SL-VIK
